[build]
command = "npm run build"
publish = "dist"
functions = "api/functions"

[dev]
functions = "api/functions"
port = 8888

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[build.environment]
VITE_PUBLIC_URL = "https://city-guides.netlify.app"
